[book]
authors = ["Nick Danis"]
language = "en"
multilingual = false
src = "src"
title = "OTpedia"

[build]
build-dir = "docs"

[output.html]
additional-css = ["user.css"]
cname = "otpedia.nickdanis.com"
mathjax-support = true
google-analytics = "G-N9DQ2L740T"

[output.html.print]
enable = false

# [preprocessor.mathjax]
# renderers = ["html"]  # mathjax only makes sense with the HTML renderer

# [preprocessor.classy]

# [preprocessor.graphviz]
# command = "mdbook-graphviz"

[preprocessor.bib]
bibliography = "library.bib"
title = "References"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]



