[book]
authors = ["Nick Danis"]
language = "en"
multilingual = false
src = "src"
title = "OTpedia"

[build]
build-dir = "docs"

[output.html]
additional-css = ["theme\\css\\user.css"]

[preprocessor.graphviz]
command = "mdbook-graphviz"

[preprocessor.classy]